// Game Database - Re-exports from database.mjs for backward compatibility
import {
  GAME_DATABASE,
  getGames,
  getGame,
  getGameBySlug,
  getGamesByGenre,
  getGamesByProvider,
  getInstalledGames,
  getFavoriteGames,
  getRecentlyPlayedGames,
  getPopularGames,
  searchGames,
  getGamesBySort,
  getUniqueGenres,
  getUniqueProviders,
  getUniqueTags,
  launchGame,
  getGameByAppId,
} from "./database.mjs";

export {
  GAME_DATABASE,
  getGames,
  getGame,
  getGameBySlug,
  getGamesByGenre,
  getGamesByProvider,
  getInstalledGames,
  getFavoriteGames,
  getRecentlyPlayedGames,
  getPopularGames,
  searchGames,
  getGamesBySort,
  getUniqueGenres,
  getUniqueProviders,
  getUniqueTags,
  launchGame,
  getGameByAppId,
};
